[tool.poetry]
name = "cp-badges"
version = "0.1.0"
description = "Competitive Programming badges"
authors = ["Joonhyung Shin <tonyshin@kaist.ac.kr>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^1.1.2"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
